### ISSUE TITLE
Missing item type for some arrays causes problems with OpenApi generator

### ISSUE THREAD

**Issue by juanlubf** [dealloc/helldivers2-api#10]
The OpenApi JSON file is missing some item types for some arrays (`waypoints, planet_permanent_effects, capitals, active_election_policy_effects, community_targets and planet_active_effects`), which causes Kotlin client generator to not be able to determine the List type:
<img width="873" alt="image" src="https://github.com/dealloc/helldivers2-api/assets/11267762/f5dae719-a46c-489a-80e7-00f15f0054c5">

This can easily be fixed by adding in the schema the item type for each array:
```
"waypoints": {
    "description": "Waypoints, seems to link planets together but purpose unclear",
    "type": "array",
    "items": {
        "type": "integer"
    }
}
``` 

I know most of the fields I mentioned are not known very well currently, but, just as a default type, could you add String or Intenger to avoid this kind of errors? 

Thanks!

**Comment by Kejax** [comment]
Regarding the waypoints property of the API. It seems that the waypoints are the supply lines, you can see them on https://helldivers.io if you enable the supply lines view

**Comment by dealloc** [comment]
@Kejax I've experimented with resolving the waypoints, however since it leads to recursive parsing (as all waypoints eventually form up in a circle) it would create a lot of problems.
The only solution then would be to at *some* level decide to stop rendering waypoints which would make the schema inconsistent (sometimes a planet has waypoints, sometimes it doesn't).

So for the sake of consistency I'm leaving them as planet indexes, someone who needs the waypoints can map them from the indices that are returned from the API.

**Comment by dealloc** [comment]
@juanlubf can you let me know if your code generator has any more issues regarding schema typing?

**Comment by juanlubf** [comment]
Hi @dealloc , thanks for your fast response. Actually, the code generator now is working perfectly fine after your changes. 

However, I'm facing a new issue now, related to some numeric fields. As I said in my previous comment, I'm trying to use this API to build an app in Kotlin, and in Kotlin (don't know if this is the same in other languages), the maximum value for an integer is 2147483647, but in your API there are some fields typed as `integer` returning values greater than that (e.g. `hash`), which causes an exception when serializing the JSON. I just changed those fields to type `number` which translate in Kotlin to a `Double`. I don't know if this change would be a problem for your implementation.

Fields I had to change from `integer` to `number` -> `hash, portrait_id_32, message_id_32, title_32`

Again, thanks for your time.

**Comment by dealloc** [comment]
@juanlubf no worries, I've changed all fields that I suspect are internal identifiers (aka `_32` fields) to `:number` which should hopefully get your code generator back on track.

I've changed a few fields you didn't mention as they are not always filled in, so they might've caused problems in the future.

You can check out the details in 9527364
hope this work!

**Comment by juanlubf** [comment]
Seems to be working perfectly!
Thanks!
