### ISSUE TITLE
Retrieving War_ID 

### ISSUE THREAD

**Issue by JFCCoding12** [dealloc/helldivers2-api#11]
Other then hard coding 801 for the War Id is there any way to pull the war id from somewhere? Just don't see changing a hard coded value every time there is a new current War ID

**Comment by dealloc** [comment]
there is, if you use `https://helldivers-2.fly.dev/api` you can get all available seasons & the current one

**Comment by JFCCoding12** [comment]
I see that but in code its self I see if I change the conf file's current war id and host that locally I see the change I made so there is no acutal api call to their servers to get the war id. It just pulls from the config file and runs with that number

**Comment by dealloc** [comment]
if your question is if AH has an API endpoint to get war seasons, then no there's no such endpoint (known)

**Comment by JFCCoding12** [comment]
so how did you come to the conclusion that it was 801 to start with?

**Comment by dealloc** [comment]
that was the endpoint the community reverse engineered from the game
