### ISSUE TITLE
Major Order Messages

### ISSUE THREAD

**Issue by sebsebmc** [dealloc/helldivers2-api#12]
The current major order text has all the text in the title field with a newline. Im not sure if this was a backend change on the part of Arrowhead or not. Also not seeing the newest messages since the liberation of Tien Kwan.

**Comment by sebsebmc** [comment]
Any idea where the rest of the messages come from? There were multiple new messages that showed up in the game but never appeared in the status.

**Comment by dealloc** [comment]
no idea, if they aren't available in the endpoints we know off I wouldn't know where they come from.
The people who reverse engineered the game aren't willing to share their work either

**Comment by sebsebmc** [comment]
And now Im getting just a title for the Weapons Experimentation effect thats ongoing.

**Comment by dealloc** [comment]
a quick peek in Postman reveals that their API essentially sends nothing to work with unfortunately
![image](https://github.com/dealloc/helldivers2-api/assets/2164354/3840c8c2-b471-404b-80ee-5c1c386d42db)
