### ISSUE TITLE
Data stopped updating

### ISSUE THREAD

**Issue by sebsebmc** [dealloc/helldivers2-api#13]
Data has been stale for the last hour. If you look at https://github.com/sebsebmc/helldivers-history/actions and under the scheduled job "Commit and push if it changed" there are multiple runs that had no new data. Is this a fallback of some sort?

**Comment by sebsebmc** [comment]
https://helldivers.io does also appear to be breaking right now so I assume the underlying data is getting messed up or broke sume assumption.

**Comment by sebsebmc** [comment]
The in-game war progress is similarly frozen so it appears this is not a gault of the relay server but of the actual game backend servers. Feel free to close (or leave open to prevent more issues being opened for now)

**Comment by dealloc** [comment]
We'll leave this open until resolved, in the hopes the community finds a solution/workaround

**Comment by sebsebmc** [comment]
Data seems to be coming back. Not sure there is much chance of a workaround when the devs froze the way state intentionally.

**Comment by dealloc** [comment]
Given this API is essentially a fancy proxy for AH's endpoints not much that can be done when they freeze the API endpoints..
