### ISSUE TITLE
language code

### ISSUE THREAD

**Issue by deluxghost** [dealloc/helldivers2-api#14]
`zh-Hans` and `zh-Hant` are also valid `Accept-Language` values

**Comment by dealloc** [comment]
due to the design choice of using 2 letter ISO codes, I can only add one (1) entry for `zh`.
Is there a preference as to which of the two would be more suitable for the largest audience?

**Comment by deluxghost** [comment]
Although it's still better to have both (like what Steam does), but more people use the simplified one `zh-Hans`, and most of Chinese speaker can read both

**Comment by dealloc** [comment]
I'll keep it in mind if we ever decide to change the system from a 2 letter ISO system
