### ISSUE TITLE
How do you pull current stats for helldivers2

### ISSUE THREAD

**Issue by Nbc66** [dealloc/helldivers2-api#18]
Im confused by the way you get the current stats of a planet or a war campaign

As im not familiar with elixer i cant seem to find where you actually pull the stats from

**Comment by dealloc** [comment]
hi @Nbc66 the information is pulled here: [info](https://github.com/dealloc/helldivers2-api/blob/b31928dd54913e3f3b773cec1e769d8c1e430d26/lib/helldivers_2/models/war_info.ex#L31) & [status](https://github.com/dealloc/helldivers2-api/blob/b31928dd54913e3f3b773cec1e769d8c1e430d26/lib/helldivers_2/models/war_status.ex#L110)
