### ISSUE TITLE
Additional Endpoints

### ISSUE THREAD

**Issue by LordOfPolls** [dealloc/helldivers2-api#23]
Hey, I work on the rust wrapper for the helldivers api, in the spirit of cooperation there are two endpoints i dont think you use yet 

`https://api.live.prod.thehelldiversgame.com/api/NewsFeed/[war_id]`
```
[{"id":2797,"published":2414563,"type":0,"tagIds":[]},{"id":2798,"published":2499000,"type":0,"tagIds":[]},{"id":2799,"published":2507100,"type":0,"tagIds":[]},{"id":2800,"published":2531100,"type":0,"tagIds":[]},{"id":2801,"published":2598240,"type":0,"tagIds":[]},{"id":2802,"published":2705219,"type":0,"tagIds":[]},{"id":2803,"published":2705235,"type":0,"tagIds":[]},{"id":2804,"published":2822793,"type":0,"tagIds":[]},{"id":2805,"published":2899259,"type":0,"tagIds":[]},{"id":2806,"published":2899330,"type":0,"tagIds":[]}]
```

and 

`https://api.live.prod.thehelldiversgame.com/api/WarSeason/[war_id]/WarTime`

```
{"time":3120460}
```

**Comment by dealloc** [comment]
Thanks for the heads up!
What purpose does the `WarTime` serve compared to the timestamp returned in the war status?

I actually added support for the newsfeed yesterday after someone in the Discord notified me of it

**Comment by LordOfPolls** [comment]
To be candid, I have no idea for a use outside of the game for `WarTime` - especially seeing as `Status` is pretty painless. 
I only support it because 1-it exists, and 2- someone out there might want it

**Comment by dealloc** [comment]
fair enough, appreciate the heads up!
Feel free to let me know if you find any more endpoints, or head on over to https://discord.gg/y48gx4fB and share it there
