### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by sebsebmc** [dealloc/helldivers2-api#4]
Im currently git-scraping the API and occasionally getting error responses for `/api/801/status`: 
```
{"errors":{"detail":"Not Found"}}
```
If you are caching results it would be good to attempt to drop these error responses, serve either old data and attempt to fetch new data (reasonable rate limits considered).

**Comment by dealloc** [comment]
@sebsebmc I've made some changes to the hosting it runs on, are you still running into problems regarding container startup?

**Comment by sebsebmc** [comment]
I'll need to check the history to see how often it erred but I'm definitely get rate limit responses.

**Comment by sebsebmc** [comment]
You can see the history of the helldivers.json file here https://github.com/sebsebmc/helldivers-history

**Comment by dealloc** [comment]
Odd, but if more people are using Github IP's to scrap the API you might be hitting those rate limits.

My question are more regarding if you got 404 errors (due to the application restarting and not being ready yet)

**Comment by sebsebmc** [comment]
Going back 9 hours it looks mostly to be rate limit errors rather than not found. Haven't seen the error show up in a quick skim.

**Comment by dealloc** [comment]
I can see about increasing the rate limit now that the API has a bit more breathing room in resources, but that's not guaranteed to fix all those problems

**Comment by dealloc** [comment]
@sebsebmc I've increased rate limit (10x), let me know if the problem persists for you

**Comment by sebsebmc** [comment]
Yeah, I need to setup analysis of the logging but I do think it has helped, no rate limit issues in the last hour or so

**Comment by dealloc** [comment]
Awesome, I'll be closing this then.
If you run into any trouble along the way in the future feel free to open a new ticket
