### ISSUE TITLE
Planet Details

### ISSUE THREAD

**Issue by twashburn456** [dealloc/helldivers2-api#6]
First of all, great effort so far. I have been breaking down the API as well but unfortunately I haven't been able to fuzz out a planet's endpoint. I did break out a file from the game (generated_planet_data.dl_bin) which does list 385 planets with there corresponding biomes if you are interested in that information but unfortunately I don't think there is any specific names in that file just the IDs.

**Comment by dealloc** [comment]
that's awesome! it's actually better to have the ID's rather than the names as that's what's used internally to link information!

I'd love it if you could share that information :)
